services:
  db:
    image: postgres:15
    container_name: peluqueria_db
    environment:
      POSTGRES_DB: peluqueria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./peluqueria-api
    container_name: peluqueria_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/peluqueria_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db

  client:
    build:
      context: ./peluqueria-client
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    container_name: peluqueria_client
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  postgres_data:
