services:
  - type: web
    name: peluqueria-saas-prod-fra
    runtime: docker
    repo: https://github.com/AlexRg32/peluqueria-saas
    plan: free
    region: frankfurt
    rootDir: peluqueria-api
    branch: main
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: peluqueria-saas-staging-fra
    runtime: docker
    repo: https://github.com/AlexRg32/peluqueria-saas
    plan: free
    region: frankfurt
    rootDir: peluqueria-api
    branch: staging
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: staging
